/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace KindlinkCampaign {
  export type CampaignStruct = {
    offchainId: string;
    creator: AddressLike;
    goalAmount: BigNumberish;
    raisedAmount: BigNumberish;
    status: BigNumberish;
    withdrawRequested: boolean;
    exists: boolean;
  };

  export type CampaignStructOutput = [
    offchainId: string,
    creator: string,
    goalAmount: bigint,
    raisedAmount: bigint,
    status: bigint,
    withdrawRequested: boolean,
    exists: boolean
  ] & {
    offchainId: string;
    creator: string;
    goalAmount: bigint;
    raisedAmount: bigint;
    status: bigint;
    withdrawRequested: boolean;
    exists: boolean;
  };
}

export interface KindlinkCampaignInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "approveWithdraw"
      | "claimRefund"
      | "createCampaign"
      | "donate"
      | "getCampaign"
      | "getCampaignKey"
      | "getContractBalance"
      | "getDonation"
      | "markFailed"
      | "markSuccess"
      | "owner"
      | "platformFeeBps"
      | "platformWallet"
      | "renounceOwnership"
      | "requestWithdraw"
      | "setPlatformFee"
      | "setPlatformWallet"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignMarkedFailed"
      | "CampaignMarkedSuccess"
      | "Donated"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
      | "PlatformWalletUpdated"
      | "RefundClaimed"
      | "WithdrawApproved"
      | "WithdrawRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "donate", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonation",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markFailed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markSuccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markFailed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignKey: BytesLike,
    offchainId: string,
    creator: AddressLike,
    goalAmount: BigNumberish
  ];
  export type OutputTuple = [
    campaignKey: string,
    offchainId: string,
    creator: string,
    goalAmount: bigint
  ];
  export interface OutputObject {
    campaignKey: string;
    offchainId: string;
    creator: string;
    goalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignMarkedFailedEvent {
  export type InputTuple = [campaignKey: BytesLike];
  export type OutputTuple = [campaignKey: string];
  export interface OutputObject {
    campaignKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignMarkedSuccessEvent {
  export type InputTuple = [campaignKey: BytesLike];
  export type OutputTuple = [campaignKey: string];
  export interface OutputObject {
    campaignKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonatedEvent {
  export type InputTuple = [
    campaignKey: BytesLike,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignKey: string,
    donor: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignKey: string;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformWalletUpdatedEvent {
  export type InputTuple = [newWallet: AddressLike];
  export type OutputTuple = [newWallet: string];
  export interface OutputObject {
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    campaignKey: BytesLike,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignKey: string,
    donor: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignKey: string;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawApprovedEvent {
  export type InputTuple = [
    campaignKey: BytesLike,
    creator: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    campaignKey: string,
    creator: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    campaignKey: string;
    creator: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawRequestedEvent {
  export type InputTuple = [campaignKey: BytesLike, creator: AddressLike];
  export type OutputTuple = [campaignKey: string, creator: string];
  export interface OutputObject {
    campaignKey: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KindlinkCampaign extends BaseContract {
  connect(runner?: ContractRunner | null): KindlinkCampaign;
  waitForDeployment(): Promise<this>;

  interface: KindlinkCampaignInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  approveWithdraw: TypedContractMethod<
    [campaignKey: BytesLike],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [campaignKey: BytesLike],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [offchainId: string, creator: AddressLike, goalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[campaignKey: BytesLike], [void], "payable">;

  getCampaign: TypedContractMethod<
    [campaignKey: BytesLike],
    [KindlinkCampaign.CampaignStructOutput],
    "view"
  >;

  getCampaignKey: TypedContractMethod<[offchainId: string], [string], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getDonation: TypedContractMethod<
    [campaignKey: BytesLike, donor: AddressLike],
    [bigint],
    "view"
  >;

  markFailed: TypedContractMethod<
    [campaignKey: BytesLike],
    [void],
    "nonpayable"
  >;

  markSuccess: TypedContractMethod<
    [campaignKey: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestWithdraw: TypedContractMethod<
    [campaignKey: BytesLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformWallet: TypedContractMethod<
    [newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveWithdraw"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [offchainId: string, creator: AddressLike, goalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignKey: BytesLike],
    [KindlinkCampaign.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignKey"
  ): TypedContractMethod<[offchainId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDonation"
  ): TypedContractMethod<
    [campaignKey: BytesLike, donor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "markFailed"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markSuccess"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<[campaignKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[newWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignMarkedFailed"
  ): TypedContractEvent<
    CampaignMarkedFailedEvent.InputTuple,
    CampaignMarkedFailedEvent.OutputTuple,
    CampaignMarkedFailedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignMarkedSuccess"
  ): TypedContractEvent<
    CampaignMarkedSuccessEvent.InputTuple,
    CampaignMarkedSuccessEvent.OutputTuple,
    CampaignMarkedSuccessEvent.OutputObject
  >;
  getEvent(
    key: "Donated"
  ): TypedContractEvent<
    DonatedEvent.InputTuple,
    DonatedEvent.OutputTuple,
    DonatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformWalletUpdated"
  ): TypedContractEvent<
    PlatformWalletUpdatedEvent.InputTuple,
    PlatformWalletUpdatedEvent.OutputTuple,
    PlatformWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawApproved"
  ): TypedContractEvent<
    WithdrawApprovedEvent.InputTuple,
    WithdrawApprovedEvent.OutputTuple,
    WithdrawApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawRequested"
  ): TypedContractEvent<
    WithdrawRequestedEvent.InputTuple,
    WithdrawRequestedEvent.OutputTuple,
    WithdrawRequestedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(bytes32,string,address,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignMarkedFailed(bytes32)": TypedContractEvent<
      CampaignMarkedFailedEvent.InputTuple,
      CampaignMarkedFailedEvent.OutputTuple,
      CampaignMarkedFailedEvent.OutputObject
    >;
    CampaignMarkedFailed: TypedContractEvent<
      CampaignMarkedFailedEvent.InputTuple,
      CampaignMarkedFailedEvent.OutputTuple,
      CampaignMarkedFailedEvent.OutputObject
    >;

    "CampaignMarkedSuccess(bytes32)": TypedContractEvent<
      CampaignMarkedSuccessEvent.InputTuple,
      CampaignMarkedSuccessEvent.OutputTuple,
      CampaignMarkedSuccessEvent.OutputObject
    >;
    CampaignMarkedSuccess: TypedContractEvent<
      CampaignMarkedSuccessEvent.InputTuple,
      CampaignMarkedSuccessEvent.OutputTuple,
      CampaignMarkedSuccessEvent.OutputObject
    >;

    "Donated(bytes32,address,uint256)": TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;
    Donated: TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "PlatformWalletUpdated(address)": TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
    PlatformWalletUpdated: TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;

    "RefundClaimed(bytes32,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "WithdrawApproved(bytes32,address,uint256,uint256)": TypedContractEvent<
      WithdrawApprovedEvent.InputTuple,
      WithdrawApprovedEvent.OutputTuple,
      WithdrawApprovedEvent.OutputObject
    >;
    WithdrawApproved: TypedContractEvent<
      WithdrawApprovedEvent.InputTuple,
      WithdrawApprovedEvent.OutputTuple,
      WithdrawApprovedEvent.OutputObject
    >;

    "WithdrawRequested(bytes32,address)": TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
    WithdrawRequested: TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
  };
}
